### PR TITLE
Fold VerilogModulusCleanup into LegalizeVerilog

### LINKED ISSUE #2129: crash 2651
### Checklist

- [x] Did you specify the current behavior?
- [x] Did you specify the expected behavior?
- [x] Did you provide a code example showing the problem?
- [x] Did you describe your environment?
- [ ] Did you specify relevant external information?

### What is the current behavior?

The following FIRRTL program.

```python
; seed: 2651
circuit top_mod :
  module top_mod :
    input clock: Clock
    wire _tmp18: SInt<2>
    wire _tmp27: SInt<24>
    _tmp18 <= rem(asSInt(UInt<21>(932719)), SInt<2>("b-10"))
    _tmp27 <= add(_tmp18, SInt<23>("o-15035672"))
    assert(clock, xorr(UInt<16>("h4045")), xorr(_tmp27), "assert31")
```

Running with `firrtl-1.5.0-SNAPSHOT` crashes with the following error:

```
firrtl
Exception in thread "main" firrtl.FirrtlInternalException: Internal Error! trying to emit unsupported operator: UnknownType
Please file an issue at https://github.com/ucb-bar/firrtl/issues
        at firrtl.Utils$.error(Utils.scala:491)
        at firrtl.Utils$.throwInternalError(Utils.scala:164)
        at firrtl.VerilogEmitter.emitCol(VerilogEmitter.scala:205)
        at firrtl.VerilogEmitter.$anonfun$emitCol$2(VerilogEmitter.scala:197)
        at firrtl.VerilogEmitter.$anonfun$emitCol$2$adapted(VerilogEmitter.scala:196)
        at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
        at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:165)
        at scala.collection.immutable.List.foldLeft(List.scala:79)
        at firrtl.VerilogEmitter.emitCol(VerilogEmitter.scala:196)
        at firrtl.VerilogEmitter.$anonfun$emitCol$2(VerilogEmitter.scala:197)
        at firrtl.VerilogEmitter.$anonfun$emitCol$2$adapted(VerilogEmitter.scala:196)
        at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
        at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:165)
        at scala.collection.immutable.List.foldLeft(List.scala:79)
        at firrtl.VerilogEmitter.emitCol(VerilogEmitter.scala:196)
        at firrtl.VerilogEmitter.emit(VerilogEmitter.scala:124)
        at firrtl.VerilogEmitter$VerilogRender.$anonfun$emit_streams$6(VerilogEmitter.scala:1106)
        at firrtl.VerilogEmitter$VerilogRender.$anonfun$emit_streams$6$adapted(VerilogEmitter.scala:1106)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
        at firrtl.VerilogEmitter$VerilogRender.emit_streams(VerilogEmitter.scala:1106)
        at firrtl.VerilogEmitter$VerilogRender.emit_verilog(VerilogEmitter.scala:1226)
        at firrtl.VerilogEmitter.$anonfun$emit$2(VerilogEmitter.scala:1267)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at firrtl.VerilogEmitter.emit(VerilogEmitter.scala:1261)
        at firrtl.VerilogEmitter.$anonfun$execute$2(VerilogEmitter.scala:1279)
        at scala.collection.immutable.List.flatMap(List.scala:293)
        at scala.collection.immutable.List.flatMap(List.scala:79)
        at firrtl.VerilogEmitter.execute(VerilogEmitter.scala:1276)
        at firrtl.SystemVerilogEmitter.execute(SystemVerilogEmitter.scala:29)
        at firrtl.Transform.transform(Compiler.scala:319)
        at firrtl.Transform.transform$(Compiler.scala:319)
        at firrtl.SeqTransform.transform(Compiler.scala:401)
        at firrtl.stage.transforms.ExpandPrepares.execute(ExpandPrepares.scala:19)
        at firrtl.Transform.transform(Compiler.scala:319)
        at firrtl.Transform.transform$(Compiler.scala:319)
        at firrtl.stage.transforms.ExpandPrepares.transform(ExpandPrepares.scala:7)
        at firrtl.stage.transforms.CatchCustomTransformExceptions.execute(CatchCustomTransformExceptions.scala:10)
        at firrtl.Transform.transform(Compiler.scala:319)
        at firrtl.Transform.transform$(Compiler.scala:319)
        at firrtl.stage.transforms.CatchCustomTransformExceptions.transform(CatchCustomTransformExceptions.scala:7)
        at firrtl.stage.transforms.UpdateAnnotations.$anonfun$internalTransform$1(UpdateAnnotations.scala:22)
        at firrtl.Utils$.time(Utils.scala:170)
        at firrtl.Transform$.runTransform(Compiler.scala:217)
        at firrtl.stage.transforms.UpdateAnnotations.internalTransform(UpdateAnnotations.scala:22)
        at firrtl.stage.transforms.UpdateAnnotations.internalTransform(UpdateAnnotations.scala:8)
        at firrtl.options.Translator.transform(Phase.scala:248)
        at firrtl.options.Translator.transform$(Phase.scala:248)
        at firrtl.stage.transforms.UpdateAnnotations.transform(UpdateAnnotations.scala:8)
        at firrtl.options.DependencyManager.$anonfun$transform$3(DependencyManager.scala:278)
        at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
        at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:165)
        at scala.collection.immutable.List.foldLeft(List.scala:79)
        at firrtl.options.DependencyManager.transform(DependencyManager.scala:269)
        at firrtl.options.DependencyManager.transform$(DependencyManager.scala:255)
        at firrtl.stage.TransformManager.transform(TransformManager.scala:14)
        at firrtl.stage.phases.Compiler.$anonfun$internalTransform$6(Compiler.scala:120)
        at firrtl.Utils$.time(Utils.scala:170)
        at firrtl.stage.phases.Compiler.f$1(Compiler.scala:120)
        at firrtl.stage.phases.Compiler.$anonfun$internalTransform$8(Compiler.scala:125)
        at scala.collection.immutable.List.map(List.scala:246)
        at scala.collection.immutable.List.map(List.scala:79)
        at firrtl.stage.phases.Compiler.internalTransform(Compiler.scala:125)
        at firrtl.stage.phases.Compiler.internalTransform(Compiler.scala:45)
        at firrtl.options.Translator.transform(Phase.scala:248)
        at firrtl.options.Translator.transform$(Phase.scala:248)
        at firrtl.stage.phases.Compiler.transform(Compiler.scala:45)
        at firrtl.stage.phases.CatchExceptions.transform(CatchExceptions.scala:30)
        at firrtl.stage.phases.CatchExceptions.transform(CatchExceptions.scala:17)
        at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:38)
        at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:15)
        at firrtl.options.Translator.transform(Phase.scala:248)
        at firrtl.options.Translator.transform$(Phase.scala:248)
        at firrtl.options.phases.DeletedWrapper.transform(DeletedWrapper.scala:15)
        at firrtl.options.DependencyManager.$anonfun$transform$3(DependencyManager.scala:278)
        at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
        at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:165)
        at scala.collection.immutable.List.foldLeft(List.scala:79)
        at firrtl.options.DependencyManager.transform(DependencyManager.scala:269)
        at firrtl.options.DependencyManager.transform$(DependencyManager.scala:255)
        at firrtl.options.PhaseManager.transform(DependencyManager.scala:436)
        at firrtl.stage.FirrtlStage.run(FirrtlStage.scala:38)
        at firrtl.options.Stage$$anon$1.transform(Stage.scala:43)
        at firrtl.options.Stage$$anon$1.transform(Stage.scala:43)
        at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:38)
        at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:15)
        at firrtl.options.Translator.transform(Phase.scala:248)
        at firrtl.options.Translator.transform$(Phase.scala:248)
        at firrtl.options.phases.DeletedWrapper.transform(DeletedWrapper.scala:15)
        at firrtl.options.Stage.$anonfun$transform$5(Stage.scala:47)
        at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
        at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:165)
        at scala.collection.immutable.List.foldLeft(List.scala:79)
        at firrtl.options.Stage.$anonfun$transform$3(Stage.scala:47)
        at logger.Logger$.$anonfun$makeScope$2(Logger.scala:166)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
        at logger.Logger$.makeScope(Logger.scala:164)
        at firrtl.options.Stage.transform(Stage.scala:47)
        at firrtl.options.Stage.execute(Stage.scala:58)
        at firrtl.options.StageMain.main(Stage.scala:71)
        at firrtl.stage.FirrtlMain.main(FirrtlStage.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at coursier.bootstrap.launcher.a.a(Unknown Source)
        at coursier.bootstrap.launcher.Launcher.main(Unknown Source)
```

### What is the expected behavior?

Not to crash. Give a more informative Error or Warning or just work.

### Steps to Reproduce

`./firrtl-1.5.0-SNAPSHOT -i top_mod.fir`

### Your environment

`Linux linux-sydi 5.11.4-1-default #1 SMP Mon Mar 8 05:16:55 UTC 2021 (be77cd2) x86_64 x86_64 x86_64 GNU/Linux`

- Verilator version: `Verilator 4.109 devel rev v4.108-38-g36eb952b`

### LINKED ISSUE #2287: Why do modulus(%) and compare(===/<=/>=) operators combinations lead to firrtl.FirrtlInternalException?
### Checklist

- [x] Did you specify the current behavior?
- [x] Did you specify the expected behavior?
- [x] Did you provide a code example showing the problem?
- [x] Did you describe your environment?
- [x] Did you specify relevant external information?

### What is the current behavior?
Can not generate Verilog, and emit some firrtl exceptions.  
### What is the expected behavior?
Generate Verilog successfully.
### Steps to Reproduce
I have a module in which a modulus operator % is combined with a compare operators such as ===/<=/>=.
When I tried to generate Verilog code for this module, I got a **firrtl.FirrtlInternalException**.
Here is a trivial module can reproduce this issue:
```scala
package modulus

import chisel3._

class Modulus extends Module {
    val io = IO(new Bundle{
        val in1 = Input(SInt(8.W))
        val in2 = Input(SInt(8.W))
        val out = Output(Bool())
    })
    io.out := ((io.in1 % io.in2) === 0.S)
} 

object Modulus extends App {
    val verilogString = (new chisel3.stage.ChiselStage).emitVerilog(new Modulus, Array.concat(args, Array("-td=./verilog-output")))
}
```

And I got the following messages:
```scala
[info] running modulus.Modulus 
Elaborating design...
Done elaborating.
[error] (run-main-11) firrtl.FirrtlInternalException: Internal Error! Unexpected non-SInt type for Reference(_io_out_T,UIntType(IntWidth(8)),NodeKind,SourceFlow) in DoPrim(eq,ArrayBuffer(Reference(_io_out_T,UIntType(IntWidth(8)),NodeKind,SourceFlow), SIntLiteral(0,IntWidth(8))),ArrayBuffer(),UnknownType)
[error] Please file an issue at https://github.com/ucb-bar/firrtl/issues
[error] firrtl.FirrtlInternalException: Internal Error! Unexpected non-SInt type for Reference(_io_out_T,UIntType(IntWidth(8)),NodeKind,SourceFlow) in DoPrim(eq,ArrayBuffer(Reference(_io_out_T,UIntType(IntWidth(8)),NodeKind,SourceFlow), SIntLiteral(0,IntWidth(8))),ArrayBuffer(),UnknownType)
[error] Please file an issue at https://github.com/ucb-bar/firrtl/issues
[error]         at firrtl.Utils$.error(Utils.scala:491)
[error]         at firrtl.Utils$.throwInternalError(Utils.scala:164)
[error]         at firrtl.VerilogEmitter.castIf$1(VerilogEmitter.scala:279)
[error]         at firrtl.VerilogEmitter.op_stream(VerilogEmitter.scala:324)
[error]         at firrtl.VerilogEmitter.emitCol(VerilogEmitter.scala:165)
[error]         at firrtl.VerilogEmitter.$anonfun$emitCol$2(VerilogEmitter.scala:204)
[error]         at firrtl.VerilogEmitter.$anonfun$emitCol$2$adapted(VerilogEmitter.scala:203)
[error]         at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
[error]         at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
[error]         at scala.collection.immutable.List.foldLeft(List.scala:91)
………………
```

### Your environment
Chisel Version: 3.4.3
Verilator Version: 4.016 2019-06-16 rev UNKNOWN_REV
OS: Linux 5.4.0-52-generic #57~18.04.1-Ubuntu SMP Thu Oct 15 14:04:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### External Information
And we also report this problem at [Chisel3 disscussion pane](https://github.com/chipsalliance/chisel3/discussions/1998).

### LINKED ISSUE #2480: Failed to emit Verilog when using the modulus operator.
### Checklist

- [X] Did you specify the current behavior?
- [X] Did you specify the expected behavior?
- [X] Did you provide a code example showing the problem?
- [X] Did you describe your environment?
- [X] Did you specify relevant external information?

### What is the current behavior?
I get this error on Chisel when trying to emit the Verilog code of a module that uses the modulus operator inside a switch operator.

```
firrtl.FirrtlInternalException: Internal Error! trying to emit unsupported operator: UnknownType
Please file an issue at https://github.com/ucb-bar/firrtl/issues
	at firrtl.Utils$.error(Utils.scala:471)
	at firrtl.Utils$.throwInternalError(Utils.scala:175)
	at firrtl.VerilogEmitter.emitCol(VerilogEmitter.scala:221)
	at firrtl.VerilogEmitter.$anonfun$emitCol$2(VerilogEmitter.scala:213)
	at firrtl.VerilogEmitter.$anonfun$emitCol$2$adapted(VerilogEmitter.scala:212)
        ...
```

Chisel code for the module:
```
import chisel3._
import chisel3.util._
import chisel3.stage.ChiselStage

class ALU_test(width: Int) extends Module {
  val io = IO(new Bundle {
    val op = Input(
      UInt(8.W)
    )
    val in1 = Input(SInt(width.W)) 
    val in2 = Input(SInt(width.W)) 
    val res = Output(SInt(width.W))
  })
  io.res := 0.S(width.W)
  switch(io.op) {
    is(0.U) { io.res := io.in1 + io.in2 }
    is(1.U) { io.res := io.in1 - io.in2 }
    is(2.U) { io.res := io.in1 % io.in2 } 
  }
}
```

### What is the expected behavior?
Before updating my project to Chisel 3.5.0 the Verilog code was generated without a problem. 

### Steps to Reproduce
This Scastie shows the complete error log:
https://scastie.scala-lang.org/4dIFyeXeQPiisTZrLLI9JQ

Apparently FIRRTL can't infer the width of the result. My quick fix was to replace `io.in1 % io.in2` for `0.S(64.W)+(io.in1%io.in2 )` as it forces the width to be 64 and the program emits the Verilog code correctly .

### Your environment
- Chisel Version:  3.5.0
- FIRRTL Version: 1.5.0
- OS: Ubuntu 20.04

### External Information
Might be related to: #2129

### PR DESCRIPTION
**Pull request by jackkoenig**
This fixes handling of signed modulus and removes some redundant work.

Fixes #2480, Fixes #2129, Fixes #2287, Fixes https://github.com/chipsalliance/chisel3/issues/2012

This has been a bug for a long time. I've marked it 1.4.x but even that might be a pain to merge due to conflicts with https://github.com/chipsalliance/firrtl/pull/2304

### Contributor Checklist

- [x] Did you add Scaladoc to every public function/method?
- [NA] Did you update the FIRRTL spec to include every new feature/behavior?
- [x] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [x] Did you state the API impact?
- [x] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?
- [x] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

 - bug fix               
 - code cleanup       

#### API Impact

No impact

#### Backend Code Generation Impact

No impact

#### Desired Merge Strategy

 - Squash

#### Release Notes

Fix handling of modulus (`rem`) on SInts

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (1.2.x, 1.3.0, 1.4.0) ?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

### CODE REVIEW

File: src/main/scala/firrtl/backends/verilog/LegalizeVerilog.scala [hunk 1]
```diff
@@ -47,16 +48,44 @@ object LegalizeVerilog extends Pass {
     }
   }
 
-  import firrtl.passes.PadWidths.forceWidth
   private def getWidth(e: Expression): Int = bitWidth(e.tpe).toInt
 
+  /* Verilog has the width of (a % b) = Max(W(a), W(b))
+   * FIRRTL has the width of (a % b) = Min(W(a), W(b)), which makes more sense,
+   * but nevertheless is a problem when emitting verilog
```
Comment (seldridge) [inline src/main/scala/firrtl/backends/verilog/LegalizeVerilog.scala:55]: "which makes more sense" 👀

**Comment by jackkoenig** [comment]
> You may consider a less heavy-handed test than the equivalence test, e.g., a test of the pass behavior is likely more targeted and sufficient.

Fair, but it works so 🤷‍♂️

File: src/main/scala/firrtl/backends/verilog/LegalizeVerilog.scala (hunk 1 above)
Comment (jackkoenig) [reply src/main/scala/firrtl/backends/verilog/LegalizeVerilog.scala:55]: I just copied the comment from here 🙃 https://github.com/chipsalliance/firrtl/blob/c56e341d25e35a5207c4eea12bac9bf0ddd8b652/src/main/scala/firrtl/passes/VerilogModulusCleanup.scala#L16
