### PR TITLE
Fix width of signed addition when input to mux

### LINKED ISSUE #2439: Truncating the result of signed addition
### Checklist

- [x] Did you specify the current behavior?
- [x] Did you specify the expected behavior?
- [x] Did you provide a code example showing the problem?
- [x] Did you describe your environment?
- [x] Did you specify relevant external information?

### What is the current behavior?
```
circuit Ops:
  module Ops:
    input sel: UInt<4>
    input is: SInt<8>
    output os: SInt<9>

    os <= SInt(0)

    when eq(sel, UInt(0)):
      os <= add(is, is)
```
 produces:
 ```verilog
module ops(
  input  [3:0] sel,
  input  [7:0] is,
  output [8:0] os
);
  assign os = sel == 4'h0 ? $signed($signed(is) + $signed(is)) : $signed(9'sh0); // @[]
endmodule
```
 
The expression `$signed($signed(is) + $signed(is))` performs the addition at 8 bits instead of 9.

The following two lines of verilog are not equivalent:
```verilog
  assign os = $signed($signed(is) + $signed(is))
  assign os = $signed(is) + $signed(is);
```

---

See https://www.edaplayground.com/x/jbLq to play around with this.

```verilog
module Foo(
  input        sel,
  input  [3:0] is,
  output [4:0] out1,
  output [4:0] out2
);
  assign out1 = $signed(is) + $signed(is);
  assign out2 = sel ? $signed($signed(is) + $signed(is)) : $signed(9'sh0);
endmodule
```
```
    for (int i = 0; i < 4'hf; ++i) begin
    is = i;
    #1;
    $display("%x + %x = %x vs. %x", is, is, out1, out2);
    end
```

```
Compiler version Q-2020.03-SP1-1; Runtime version Q-2020.03-SP1-1;  Dec  9 16:17 2021
00, 00
02, 02
04, 04
06, 06
08, 18
0a, 1a
0c, 1c
0e, 1e
10, 00
12, 02
14, 04
16, 06
18, 18
1a, 1a
1c, 1c
           V C S   S i m u l a t i o n   R e p o r t 
Time: 15 ns
```
---

When the addition is not used in another expression, the outer `$signed()` cast is not present:
```
circuit Ops:
  module Ops:
    input sel: UInt<4>
    input is: SInt<8>
    output os: SInt<9>

    os <= add(is, is)
```
produces:
```
module Ops(
  input  [3:0] sel,
  input  [7:0] is,
  output [8:0] os
);
  assign os = $signed(is) + $signed(is);
endmodule
```
### What is the expected behavior?

The addition should be performed at 9 bits.

### Steps to Reproduce

Above.

### PR DESCRIPTION
**Pull request by jackkoenig**
Extremely focused fix for #2439. I'm not sure if this is the best fix but I think the test is pretty good at least so wanted to put this out there.

Fixes #2439

h/t to @youngar for finding an OG bug.

I'm wondering if it would be better to just remove the casts in the VerilogEmitter, do we ever actually need to cast the inputs to a mux? https://github.com/chipsalliance/firrtl/blob/4347f57b7ef201251fb2cd463124f2d7cea369f8/src/main/scala/firrtl/backends/verilog/VerilogEmitter.scala#L182
That's just a lot scarier of a change 😨 

I'm backporting this as far as it will go...

### Contributor Checklist

- [NA] Did you add Scaladoc to every public function/method?
- [NA] Did you update the FIRRTL spec to include every new feature/behavior?
- [x] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [x] Did you state the API impact?
- [x] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?
- [x] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

  - bug fix        

#### API Impact

No impact

#### Backend Code Generation Impact

Minimal, will split out signed addition into another Statement if it is a direct input to a mux

#### Desired Merge Strategy

 - Squash

#### Release Notes

Fix width of signed addition when it is an input to a mux.

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (1.2.x, 1.3.0, 1.4.0) ?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

### CODE REVIEW

File: src/main/scala/firrtl/passes/SplitExpressions.scala [hunk 1]
```diff
@@ -27,6 +27,11 @@ object SplitExpressions extends Pass {
     case _ => false
   }
 
+  private def isSignedAdd(e: Expression): Boolean = e match {
+    case DoPrim(PrimOps.Add, _, _, _: SIntType) => true
+    case _ => false
+  }
```
Comment (seldridge) [inline src/main/scala/firrtl/passes/SplitExpressions.scala:33]: This may be prefetching, too far, but maybe we want to do this for any arithmetic op of `SIntType`? E.g., I can produce a similar error with subtraction:

https://www.edaplayground.com/x/WAHv

Comment (jackkoenig) [reply src/main/scala/firrtl/passes/SplitExpressions.scala:33]: Definitely not prefetching too far. If you can produce the same error with other ops then we should fix those as well. I'm leaning toward the VerilogEmitter change instead since it should fix the whole class of issues but it makes me a little nervous.

**Review by seldridge — APPROVED** [review]

**Comment by jackkoenig** [comment]
Skipping formal CI because it *should* fail

**Comment by jackkoenig** [comment]
I added the label a bit late. Formal equiv for Ops failed (as it should because we're fixing it), now rerunning.
